#define UNICODE_KEY_MAC KC_LEFT_ALT
#define UNICODE_KEY_LNX LCTL(LSFT(KC_U))
#define UNICODE_KEY_WINC KC_RIGHT_ALT
#define UNICODE_CYCLE_PERSIST true
#define UNICODE_TYPE_DELAY 10
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_LINUX

#define COMBO_COUNT 15
#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define COMBO_TERM 35

//#define TAPPING_TERM 220
//#define QUICK_TAP_TERM 10
